<?php
$blogPosts = [
  [
    'slug' => 'best-time-to-visit-tanzania-safari',
    'title' => 'Best Time to Visit Tanzania for Safari: Month-by-Month Guide 2026',
    'excerpt' => 'Discover the best time to visit Tanzania for safari with our complete month-by-month guide covering wildlife viewing, Great Migration timing, weather patterns, and seasonal pricing.',
    'meta_description' => 'Discover the best time to visit Tanzania for safari. Complete month-by-month guide covering wildlife viewing, Great Migration, weather & prices for 2026.',
    'category' => 'Planning',
    'image' => '/images/blog/best-time-tanzania.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-01-15',
    'read_time' => '8 min read',
    'featured' => true,
    'keywords' => 'best time to visit Tanzania, Tanzania safari season, Great Migration timing, Tanzania dry season, Tanzania weather',
    'translations' => [
      'de' => ['title' => 'Beste Reisezeit für Tanzania Safari: Monat-für-Monat Guide 2026', 'excerpt' => 'Entdecken Sie die beste Reisezeit für eine Tanzania Safari mit unserem vollständigen Monat-für-Monat-Leitfaden über Wildtierbeobachtung, Große Migration, Wettermuster und saisonale Preise.', 'category' => 'Planung'],
      'es' => ['title' => 'Mejor Época para Visitar Tanzania en Safari: Guía Mensual 2026', 'excerpt' => 'Descubra la mejor época para visitar Tanzania en safari con nuestra guía mensual completa sobre avistamiento de fauna, Gran Migración, clima y precios de temporada.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚最佳旅行季节：2026年逐月详细指南', 'excerpt' => '通过我们完整的逐月指南，了解坦桑尼亚最佳游猎季节，涵盖野生动物观赏、大迁徙时间、天气模式和季节性价格。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Safari için En İyi Zaman: 2026 Aylık Rehberi', 'excerpt' => 'Aylık rehberimizle Tanzanya safairi için en iyi zamanı keşfedin; yaban hayatı gözlemi, Büyük Göç zamanlaması, hava koşulları ve sezonluk fiyatları kapsıyor.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'tanzania-safari-cost-budget-guide',
    'title' => 'Tanzania Safari Cost 2026: Complete Budget Breakdown & Pricing Guide',
    'excerpt' => 'How much does a Tanzania safari cost? From budget camping at $250/day to luxury lodges at $1,500/day, get a transparent breakdown of all safari expenses.',
    'meta_description' => 'Tanzania safari cost guide 2026. Budget ($250/day) to luxury ($1500/day) breakdown, hidden fees, money-saving tips & best value packages.',
    'category' => 'Planning',
    'image' => '/images/blog/safari-cost-guide.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-01-22',
    'read_time' => '10 min read',
    'featured' => false,
    'keywords' => 'Tanzania safari cost, Tanzania safari price, budget safari Tanzania, safari package prices, how much safari cost',
    'translations' => [
      'de' => ['title' => 'Tanzania Safari Kosten 2026: Vollständige Budget-Aufschlüsselung & Preisguide', 'excerpt' => 'Was kostet eine Tanzania Safari? Vom Budget-Camping bei 250 $/Tag bis zu Luxus-Lodges bei 1.500 $/Tag – eine transparente Aufschlüsselung aller Kosten.', 'category' => 'Planung'],
      'es' => ['title' => 'Costo de Safari en Tanzania 2026: Desglose Completo de Presupuesto', 'excerpt' => '¿Cuánto cuesta un safari en Tanzania? Desde camping económico a 250$/día hasta lodges de lujo a 1.500$/día, con desglose transparente de todos los gastos.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚游猎费用2026：完整预算分解与价格指南', 'excerpt' => '坦桑尼亚游猎需要多少钱？从每天250美元的经济型露营到每天1500美元的豪华帐篷，透明展示所有费用。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Safari Maliyeti 2026: Eksiksiz Bütçe Analizi ve Fiyat Rehberi', 'excerpt' => 'Tanzanya safarisi ne kadar tutar? Günlük 250$\'lık bütçe kampingten günlük 1.500$\'lık lüks konaklama seçeneklerine kadar tüm harcamaların şeffaf dökümü.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'serengeti-national-park-safari-guide',
    'title' => 'Serengeti National Park: Ultimate Safari Guide & Great Migration',
    'excerpt' => 'Everything you need to know about planning a Serengeti safari. From the Great Migration to Big Five encounters, discover Africa\'s most iconic wildlife destination.',
    'meta_description' => 'Ultimate Serengeti safari guide. Great Migration calendar, wildlife viewing, best routes, accommodation & planning tips for 2026.',
    'category' => 'Destinations',
    'image' => '/images/blog/serengeti-guide.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-01',
    'read_time' => '9 min read',
    'featured' => true,
    'keywords' => 'Serengeti safari, Serengeti National Park, Great Migration Serengeti, Serengeti wildlife, Serengeti game drive',
    'translations' => [
      'de' => ['title' => 'Serengeti Nationalpark: Ultimativer Safari-Guide & Große Migration', 'excerpt' => 'Alles, was Sie über die Planung einer Serengeti-Safari wissen müssen. Von der Großen Migration bis zu Big-Five-Begegnungen – Afrikas ikonischstes Wildtierziel.', 'category' => 'Reiseziele'],
      'es' => ['title' => 'Parque Nacional Serengeti: Guía Definitiva de Safari y Gran Migración', 'excerpt' => 'Todo lo que necesitas saber para planificar un safari en el Serengeti. Desde la Gran Migración hasta encuentros con los Cinco Grandes, el destino más icónico de África.', 'category' => 'Destinos'],
      'zh' => ['title' => '塞伦盖蒂国家公园：终极游猎指南与大迁徙', 'excerpt' => '规划塞伦盖蒂游猎所需了解的一切。从大迁徙到非洲五霸邂逅，探索非洲最具标志性的野生动物目的地。', 'category' => '目的地'],
      'tr' => ['title' => 'Serengeti Milli Parkı: Nihai Safari Rehberi ve Büyük Göç', 'excerpt' => 'Serengeti safarisi planlamak için bilmeniz gereken her şey. Büyük Göç\'ten Büyük Beşli karşılaşmalarına kadar Afrika\'nın en ikonik yaban hayatı destinasyonu.', 'category' => 'Destinasyonlar'],
    ],
  ],
  [
    'slug' => 'ngorongoro-crater-safari-guide',
    'title' => 'Ngorongoro Crater Safari Guide: Wildlife in the World\'s Largest Caldera',
    'excerpt' => 'Explore the Ngorongoro Crater, a UNESCO World Heritage Site and home to the densest concentration of Big Five wildlife in Africa. Plan your crater descent today.',
    'meta_description' => 'Complete Ngorongoro Crater safari guide. Discover Africa\'s Eden with highest Big Five density, best viewing times, costs & expert tips.',
    'category' => 'Destinations',
    'image' => '/images/blog/ngorongoro-guide.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-05',
    'read_time' => '7 min read',
    'featured' => false,
    'keywords' => 'Ngorongoro Crater safari, Ngorongoro Conservation Area, Big Five Ngorongoro, Ngorongoro Crater tour, crater wildlife',
    'translations' => [
      'de' => ['title' => 'Ngorongoro Krater Safari-Guide: Wildtiere im weltgrößten Krater', 'excerpt' => 'Erkunden Sie den Ngorongoro-Krater, ein UNESCO-Weltkulturerbe und Heimat der dichtesten Big-Five-Population Afrikas. Planen Sie Ihren Kraberabstieg noch heute.', 'category' => 'Reiseziele'],
      'es' => ['title' => 'Guía Safari Cráter del Ngorongoro: Fauna en la Mayor Caldera del Mundo', 'excerpt' => 'Explore el Cráter del Ngorongoro, Patrimonio de la Humanidad y hogar de la mayor concentración de los Cinco Grandes de África. Planifique su descenso al cráter hoy.', 'category' => 'Destinos'],
      'zh' => ['title' => '恩戈罗恩戈罗火山口游猎指南：世界最大火山口的野生动物', 'excerpt' => '探索恩戈罗恩戈罗火山口，这里是联合国教科文组织世界遗产，拥有非洲最密集的非洲五霸野生动物群。', 'category' => '目的地'],
      'tr' => ['title' => 'Ngorongoro Krateri Safari Rehberi: Dünyanın En Büyük Kalderasında Yaban Hayatı', 'excerpt' => 'UNESCO Dünya Mirası olan ve Afrika\'nın en yoğun Büyük Beşli popülasyonuna ev sahipliği yapan Ngorongoro Krateri\'ni keşfedin.', 'category' => 'Destinasyonlar'],
    ],
  ],
  [
    'slug' => 'great-migration-tanzania-when-where',
    'title' => 'Great Migration Tanzania: When & Where to See the Wildebeest Crossings',
    'excerpt' => 'Witness the greatest wildlife spectacle on Earth. Learn exactly when and where to see the dramatic river crossings, calving season, and wildebeest movements.',
    'meta_description' => 'Great Migration Tanzania guide. When to see river crossings, calving season & where wildebeest are month-by-month in 2026.',
    'category' => 'Wildlife',
    'image' => '/images/blog/great-migration.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-08',
    'read_time' => '8 min read',
    'featured' => true,
    'keywords' => 'Great Migration Tanzania, wildebeest migration, Mara River crossing, Great Migration calendar, Serengeti migration',
    'translations' => [
      'de' => ['title' => 'Große Migration Tanzania: Wann & Wo die Gnus-Überquerungen sehen', 'excerpt' => 'Erleben Sie das größte Wildtierschauspiel der Erde. Erfahren Sie genau, wann und wo Sie die dramatischen Flussüberquerungen, die Kalbsaison und die Gnu-Bewegungen beobachten können.', 'category' => 'Wildtiere'],
      'es' => ['title' => 'Gran Migración Tanzania: Cuándo y Dónde Ver los Cruces de Ñus', 'excerpt' => 'Presencie el mayor espectáculo de fauna del planeta. Aprenda exactamente cuándo y dónde ver los dramáticos cruces de ríos, la temporada de partos y los movimientos de ñus.', 'category' => 'Fauna'],
      'zh' => ['title' => '坦桑尼亚大迁徙：何时何地观看角马渡河', 'excerpt' => '见证地球上最壮观的野生动物景观。了解观看戏剧性河流渡涉、产犊季节和角马迁徙的确切时间和地点。', 'category' => '野生动物'],
      'tr' => ['title' => 'Tanzanya Büyük Göç: GNU Geçişlerini Ne Zaman ve Nerede Görürsünüz', 'excerpt' => 'Dünyanın en büyük yaban hayatı gösterisine tanıklık edin. Dramatik nehir geçişlerini, buzağılama sezonunu ve gnu hareketlerini tam olarak ne zaman ve nerede göreceğinizi öğrenin.', 'category' => 'Yaban Hayatı'],
    ],
  ],
  [
    'slug' => 'tanzania-safari-packing-list',
    'title' => 'Tanzania Safari Packing List 2026: Essential Gear & Clothing Guide',
    'excerpt' => 'Don\'t forget a thing with our expert-curated Tanzania safari packing list. From neutral clothing to camera gear, health essentials, and season-specific tips.',
    'meta_description' => 'Complete Tanzania safari packing list 2026. Essential clothing, camera gear, health items & expert tips for Serengeti, Ngorongoro & beyond.',
    'category' => 'Planning',
    'image' => '/images/blog/packing-list.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-10',
    'read_time' => '7 min read',
    'featured' => false,
    'keywords' => 'Tanzania safari packing list, what to pack safari, safari clothing, safari essentials, Tanzania safari gear',
    'translations' => [
      'de' => ['title' => 'Tanzania Safari Packliste 2026: Ausrüstung & Kleidung Guide', 'excerpt' => 'Vergessen Sie nichts mit unserer von Experten zusammengestellten Tanzania-Safari-Packliste. Von neutraler Kleidung über Kameraausrüstung bis hin zu Gesundheitsmitteln.', 'category' => 'Planung'],
      'es' => ['title' => 'Lista de Equipaje para Safari Tanzania 2026: Guía de Ropa y Equipo Esencial', 'excerpt' => 'No olvides nada con nuestra lista de equipaje para safari en Tanzania. Ropa neutral, equipo fotográfico, artículos de salud y consejos por temporada.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚游猎行李清单2026：必备装备与服装指南', 'excerpt' => '专家精选坦桑尼亚游猎打包清单，从中性色系服装到摄影器材、健康必需品，一样都不遗漏。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Safari Bavul Listesi 2026: Temel Ekipman ve Kıyafet Rehberi', 'excerpt' => 'Uzman tarafından hazırlanan Tanzanya safari bavul listemizle hiçbir şeyi unutmayın. Nötr renkli kıyafetlerden kamera ekipmanlarına ve sağlık ihtiyaçlarına kadar.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'mount-kilimanjaro-climbing-guide',
    'title' => 'Mount Kilimanjaro Climbing Guide: Routes, Costs & Success Rates 2026',
    'excerpt' => 'Plan your Kilimanjaro summit with our comprehensive climbing guide. Compare all routes, understand costs, success rates, and get expert preparation tips.',
    'meta_description' => 'Mount Kilimanjaro climbing guide 2026. Compare routes, costs ($1800-$4000), success rates, best times & prepare for Africa\'s highest peak.',
    'category' => 'Kilimanjaro',
    'image' => '/images/blog/kilimanjaro-guide.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-12',
    'read_time' => '11 min read',
    'featured' => false,
    'keywords' => 'Kilimanjaro climbing guide, Mount Kilimanjaro routes, Kilimanjaro cost, Machame route, Kilimanjaro success rate',
    'translations' => [
      'de' => ['title' => 'Kilimanjaro Besteigungsguide: Routen, Kosten & Erfolgsquoten 2026', 'excerpt' => 'Planen Sie Ihren Kilimanjaro-Gipfel mit unserem umfassenden Kletterführer. Vergleichen Sie alle Routen, Kosten, Erfolgsquoten und erhalten Sie Expertentipps.', 'category' => 'Kilimanjaro'],
      'es' => ['title' => 'Guía de Escalada al Kilimanjaro: Rutas, Costos y Tasas de Éxito 2026', 'excerpt' => 'Planifica tu ascenso al Kilimanjaro con nuestra guía completa. Compara rutas, costos, tasas de éxito y obtén consejos expertos de preparación.', 'category' => 'Kilimanjaro'],
      'zh' => ['title' => '乞力马扎罗山攀登指南：路线、费用与成功率2026', 'excerpt' => '用我们的全面攀登指南规划您的乞力马扎罗登顶之旅。比较所有路线、了解费用、成功率，获取专家备战建议。', 'category' => '乞力马扎罗'],
      'tr' => ['title' => 'Kilimanjaro Tırmanış Rehberi: Rotalar, Maliyetler ve Başarı Oranları 2026', 'excerpt' => 'Kapsamlı tırmanış rehberimizle Kilimanjaro zirvesini planlayın. Tüm rotaları, maliyetleri, başarı oranlarını karşılaştırın ve uzman hazırlık ipuçları alın.', 'category' => 'Kilimanjaro'],
    ],
  ],
  [
    'slug' => 'tanzania-visa-requirements-vaccinations',
    'title' => 'Tanzania Visa Requirements & Vaccinations: Travel Health Guide 2026',
    'excerpt' => 'Everything you need to know about Tanzania entry requirements, tourist visas, mandatory vaccinations, malaria prevention, and travel insurance for safari.',
    'meta_description' => 'Tanzania visa & health requirements 2026. Tourist visa ($50), yellow fever vaccination, malaria prevention & travel insurance guide.',
    'category' => 'Planning',
    'image' => '/images/blog/visa-health.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-14',
    'read_time' => '6 min read',
    'featured' => false,
    'keywords' => 'Tanzania visa requirements, Tanzania vaccinations, yellow fever Tanzania, Tanzania tourist visa, malaria prevention Tanzania',
    'translations' => [
      'de' => ['title' => 'Tanzania Visaanforderungen & Impfungen: Reisegesundheitsguide 2026', 'excerpt' => 'Alles, was Sie über die Tanzania-Einreiseanforderungen, Touristenvisa, Pflichtimpfungen, Malariaschutz und Reiseversicherung für Safari wissen müssen.', 'category' => 'Planung'],
      'es' => ['title' => 'Requisitos de Visado y Vacunas para Tanzania: Guía de Salud 2026', 'excerpt' => 'Todo lo que necesitas saber sobre los requisitos de entrada a Tanzania, visados turísticos, vacunas obligatorias, prevención del paludismo y seguro de viaje.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚签证要求与疫苗接种：2026旅行健康指南', 'excerpt' => '了解坦桑尼亚入境要求、旅游签证、强制疫苗、疟疾预防和游猎旅行保险所需的一切信息。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Vize Gereksinimleri ve Aşılar: 2026 Seyahat Sağlığı Rehberi', 'excerpt' => 'Tanzanya giriş gereksinimleri, turistik vize, zorunlu aşılar, sıtma önleme ve safari seyahat sigortası hakkında bilmeniz gereken her şey.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'zanzibar-beach-holiday-after-safari',
    'title' => 'Zanzibar Beach Holiday After Safari: The Perfect Tanzania Combination',
    'excerpt' => 'Combine your Tanzania safari with a Zanzibar beach escape. Discover pristine beaches, world-class diving, historic Stone Town, and perfect safari-beach itineraries.',
    'meta_description' => 'Combine Tanzania safari with Zanzibar beach holiday. Pristine beaches, diving, Stone Town & perfect safari-beach itineraries for 2026.',
    'category' => 'Destinations',
    'image' => '/images/blog/zanzibar-beach.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-16',
    'read_time' => '8 min read',
    'featured' => false,
    'keywords' => 'Zanzibar beach holiday, safari and Zanzibar, Tanzania safari beach, Stone Town Zanzibar, Zanzibar after safari',
    'translations' => [
      'de' => ['title' => 'Sansibar Strandurlaub nach Safari: Die perfekte Tansania-Kombination', 'excerpt' => 'Kombinieren Sie Ihre Tanzania-Safari mit einem Sansibar-Strandurlaub. Entdecken Sie unberührte Strände, erstklassiges Tauchen, das historische Stone Town und perfekte Safari-Strand-Reiserouten.', 'category' => 'Reiseziele'],
      'es' => ['title' => 'Vacaciones en la Playa de Zanzíbar Después del Safari: La Combinación Perfecta', 'excerpt' => 'Combine su safari en Tanzania con escapada de playa en Zanzíbar. Playas vírgenes, buceo de clase mundial, el histórico Stone Town e itinerarios perfectos safari-playa.', 'category' => 'Destinos'],
      'zh' => ['title' => '游猎后的桑给巴尔海滩假期：坦桑尼亚完美组合', 'excerpt' => '将坦桑尼亚游猎与桑给巴尔海滩度假相结合。探索原始海滩、世界级潜水、历史悠久的石头城和完美的游猎-海滩行程。', 'category' => '目的地'],
      'tr' => ['title' => 'Safariden Sonra Zanzibar Plaj Tatili: Mükemmel Tanzanya Kombinasyonu', 'excerpt' => 'Tanzanya safarinizi Zanzibar plaj kaçamağıyla birleştirin. El değmemiş plajları, dünya standartlarında dalışı, tarihi Stone Town\'ı keşfedin.', 'category' => 'Destinasyonlar'],
    ],
  ],
  [
    'slug' => 'budget-vs-luxury-safari-tanzania',
    'title' => 'Budget vs Luxury Safari Tanzania: Which Experience is Right for You?',
    'excerpt' => 'Comparing budget camping safaris to luxury lodge experiences in Tanzania. Understand the real differences in accommodation, wildlife viewing, service, and value.',
    'meta_description' => 'Budget vs luxury safari Tanzania comparison. Costs, accommodation, wildlife viewing & service levels. Find your perfect safari style.',
    'category' => 'Planning',
    'image' => '/images/blog/budget-vs-luxury.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-02-16',
    'read_time' => '9 min read',
    'featured' => false,
    'keywords' => 'budget vs luxury safari, Tanzania safari comparison, budget safari Tanzania, luxury safari Tanzania, camping vs lodge safari',
    'translations' => [
      'de' => ['title' => 'Budget vs. Luxus Safari Tanzania: Was ist das Richtige für Sie?', 'excerpt' => 'Budget-Camping-Safaris versus Luxus-Lodge-Erlebnisse in Tanzania im Vergleich. Verstehen Sie die echten Unterschiede bei Unterkunft, Wildtierbeobachtung, Service und Wert.', 'category' => 'Planung'],
      'es' => ['title' => 'Safari Económico vs Lujo en Tanzania: ¿Cuál Experiencia es Para Usted?', 'excerpt' => 'Comparando safaris de camping económico con experiencias de lodge de lujo en Tanzania. Comprenda las diferencias reales en alojamiento, avistamiento y servicio.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚经济型与豪华游猎对比：哪种体验更适合您？', 'excerpt' => '比较坦桑尼亚经济型露营游猎与豪华帐篷营地体验，了解住宿、野生动物观赏、服务和性价比的真实差异。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya\'da Bütçe vs Lüks Safari: Hangi Deneyim Size Göre?', 'excerpt' => 'Tanzanya\'da bütçe kamp safarilerini lüks lodge deneyimleriyle karşılaştırma. Konaklama, yaban hayatı gözlemi, hizmet ve değer açısından gerçek farkları anlayın.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'tanzania-vs-kenya-safari',
    'title' => 'Tanzania vs Kenya Safari 2026: Which Country Offers the Best Safari?',
    'excerpt' => 'Tanzania or Kenya for your African safari? We compare wildlife density, park exclusivity, crowd levels, costs, and overall experience to help you decide.',
    'meta_description' => 'Tanzania vs Kenya safari: honest 2026 comparison of wildlife, costs, crowd levels, and best parks to help you choose the right destination.',
    'category' => 'Planning',
    'image' => '/images/blog/tanzania-vs-kenya-safari.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-01',
    'read_time' => '10 min read',
    'featured' => true,
    'keywords' => 'Tanzania vs Kenya safari, Kenya or Tanzania safari, best African safari country, Masai Mara vs Serengeti, Tanzania safari 2026',
    'translations' => [
      'de' => ['title' => 'Tanzania vs Kenia Safari 2026: Welches Land bietet die beste Safari?', 'excerpt' => 'Tansania oder Kenia für Ihre afrikanische Safari? Wir vergleichen Wildtierdichte, Parkexklusivität, Menschenmassen, Kosten und das Gesamterlebnis.', 'category' => 'Planung'],
      'es' => ['title' => 'Tanzania vs Kenia Safari 2026: ¿Qué País Ofrece el Mejor Safari?', 'excerpt' => '¿Tanzania o Kenia para tu safari africano? Comparamos densidad de fauna, exclusividad de parques, afluencia, costos y experiencia general.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚vs肯尼亚游猎2026：哪个国家提供最好的游猎体验？', 'excerpt' => '坦桑尼亚还是肯尼亚？我们比较野生动物密度、公园独特性、游客数量、费用和整体体验，帮您做出决定。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya vs Kenya Safari 2026: Hangi Ülke En İyi Safariyi Sunar?', 'excerpt' => 'Afrika safarisi için Tanzanya mı Kenya mı? Yaban hayatı yoğunluğu, park münhasırlığı, kalabalık seviyeleri, maliyetler ve genel deneyimi karşılaştırıyoruz.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'kilimanjaro-routes-comparison',
    'title' => 'Kilimanjaro Routes Compared: Which Route is Best for You in 2026?',
    'excerpt' => 'Machame, Lemosho, Rongai, Marangu, Umbwe or Northern Circuit? Our complete route comparison covers difficulty, success rates, scenery, cost, and best fit by experience level.',
    'meta_description' => 'Kilimanjaro routes comparison 2026. Machame vs Lemosho vs Rongai vs Marangu — difficulty, success rates, days needed & costs explained.',
    'category' => 'Kilimanjaro',
    'image' => '/images/blog/kilimanjaro-routes-comparison.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-05',
    'read_time' => '12 min read',
    'featured' => true,
    'keywords' => 'Kilimanjaro routes, best Kilimanjaro route, Machame route Kilimanjaro, Lemosho route, Rongai route, Marangu route, climb Kilimanjaro 2026',
    'translations' => [
      'de' => ['title' => 'Kilimanjaro-Routen im Vergleich: Welche Route ist 2026 die Beste?', 'excerpt' => 'Machame, Lemosho, Rongai, Marangu, Umbwe oder Northern Circuit? Unser kompletter Routenvergleich umfasst Schwierigkeit, Erfolgsraten, Landschaft, Kosten und Eignung nach Erfahrungslevel.', 'category' => 'Kilimanjaro'],
      'es' => ['title' => 'Comparación de Rutas del Kilimanjaro: ¿Cuál es la Mejor en 2026?', 'excerpt' => '¿Machame, Lemosho, Rongai, Marangu, Umbwe o Northern Circuit? Nuestra comparación completa de rutas cubre dificultad, tasas de éxito, paisajes, costos y nivel recomendado.', 'category' => 'Kilimanjaro'],
      'zh' => ['title' => '乞力马扎罗山路线对比：2026年哪条路线最适合您？', 'excerpt' => 'Machame、Lemosho、Rongai、Marangu、Umbwe还是北部环线？我们的完整路线对比涵盖难度、成功率、景色、费用和适合人群。', 'category' => '乞力马扎罗'],
      'tr' => ['title' => 'Kilimanjaro Güzergahları Karşılaştırması: 2026\'da Hangi Güzergah En İyisi?', 'excerpt' => 'Machame, Lemosho, Rongai, Marangu, Umbwe veya Kuzey Devresi? Zorlu, başarı oranları, manzara, maliyet ve deneyim seviyesine göre en uygun güzergahı bulun.', 'category' => 'Kilimanjaro'],
    ],
  ],
  [
    'slug' => 'tarangire-national-park-safari-guide',
    'title' => 'Tarangire National Park: Safari Guide, Wildlife & Best Time to Visit',
    'excerpt' => 'Discover Tarangire National Park — Tanzania\'s hidden gem famous for the largest elephant herds in Africa, ancient baobab forests, and exceptional dry-season wildlife concentrations.',
    'meta_description' => 'Tarangire National Park safari guide 2026. Largest elephant herds, baobab trees, best time to visit, what to see & how to plan your trip.',
    'category' => 'Destinations',
    'image' => '/images/blog/tarangire-national-park-safari-guide.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-08',
    'read_time' => '8 min read',
    'featured' => false,
    'keywords' => 'Tarangire National Park, Tarangire safari, Tarangire elephants, Tarangire baobab, Northern Tanzania safari, Tanzania hidden gem',
    'translations' => [
      'de' => ['title' => 'Tarangire-Nationalpark: Safari-Guide, Wildtiere & Beste Reisezeit', 'excerpt' => 'Entdecken Sie den Tarangire-Nationalpark — Tanzanias verstecktes Juwel, bekannt für die größten Elefantenherden Afrikas, uralte Baobab-Wälder und außergewöhnliche Wildtierkonzentrationen.', 'category' => 'Reiseziele'],
      'es' => ['title' => 'Parque Nacional Tarangire: Guía Safari, Fauna y Mejor Época', 'excerpt' => 'Descubra el Parque Nacional Tarangire — la joya oculta de Tanzania, famosa por las mayores manadas de elefantes de África, bosques de baobabs centenarios y concentraciones excepcionales de fauna.', 'category' => 'Destinos'],
      'zh' => ['title' => '塔兰吉雷国家公园：游猎指南、野生动物与最佳旅行时间', 'excerpt' => '探索塔兰吉雷国家公园——坦桑尼亚的隐藏宝石，以非洲最大的象群、古老的猴面包树森林和干季出色的野生动物聚集而闻名。', 'category' => '目的地'],
      'tr' => ['title' => 'Tarangire Milli Parkı: Safari Rehberi, Yaban Hayatı ve En İyi Ziyaret Zamanı', 'excerpt' => 'Afrika\'nın en büyük fil sürüleri, antik baobab ormanları ve olağanüstü kurak mevsim yaban hayatı yoğunlaşmasıyla ünlü Tarangire Milli Parkı\'nı keşfedin.', 'category' => 'Destinasyonlar'],
    ],
  ],
  [
    'slug' => 'tanzania-safari-family-guide',
    'title' => 'Tanzania Safari with Kids: The Complete Family Safari Planning Guide',
    'excerpt' => 'Planning a family safari in Tanzania? From the best parks for kids to age-appropriate activities, safety tips, and family-friendly lodges — everything parents need to know.',
    'meta_description' => 'Tanzania family safari guide 2026. Best parks for kids, age requirements, safety, family lodges & tips for the perfect family safari.',
    'category' => 'Planning',
    'image' => '/images/blog/tanzania-safari-family-guide.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-10',
    'read_time' => '9 min read',
    'featured' => false,
    'keywords' => 'Tanzania family safari, safari with kids, family safari Tanzania, children on safari, best Tanzania parks for families',
    'translations' => [
      'de' => ['title' => 'Tanzania Safari mit Kindern: Der vollständige Familiensafari-Planungsleitfaden', 'excerpt' => 'Planen Sie eine Familiensafari in Tanzania? Von den besten Parks für Kinder bis hin zu altersgerechten Aktivitäten, Sicherheitstipps und familienfreundlichen Lodges.', 'category' => 'Planung'],
      'es' => ['title' => 'Safari en Tanzania con Niños: Guía Completa de Safari Familiar', 'excerpt' => '¿Planeando un safari familiar en Tanzania? Desde los mejores parques para niños hasta actividades apropiadas por edad, consejos de seguridad y lodges familiares.', 'category' => 'Planificación'],
      'zh' => ['title' => '带孩子去坦桑尼亚游猎：完整家庭游猎规划指南', 'excerpt' => '计划坦桑尼亚家庭游猎？从最适合孩子的公园到适龄活动、安全提示和家庭友好型帐篷营地，父母需要了解的一切。', 'category' => '行程规划'],
      'tr' => ['title' => 'Çocuklarla Tanzanya Safarisi: Eksiksiz Aile Safari Planlama Rehberi', 'excerpt' => 'Tanzanya\'da aile safarisi planlamak mı istiyorsunuz? Çocuklar için en iyi parklar, yaşa uygun aktiviteler, güvenlik ipuçları ve aile dostu konaklamalar hakkında her şey.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'honeymoon-safari-tanzania',
    'title' => 'Honeymoon Safari Tanzania: The Most Romantic Safari Destinations in 2026',
    'excerpt' => 'Tanzania is the world\'s most romantic safari destination. Discover private bush camps, candlelit bush dinners, hot air balloon sunrises over the Serengeti, and luxurious Zanzibar beach finales.',
    'meta_description' => 'Tanzania honeymoon safari 2026. Romantic lodges, private camps, balloon safaris, Zanzibar beach finish & complete planning guide for couples.',
    'category' => 'Planning',
    'image' => '/images/blog/honeymoon-safari-tanzania.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-12',
    'read_time' => '8 min read',
    'featured' => false,
    'keywords' => 'honeymoon safari Tanzania, Tanzania romantic safari, Serengeti honeymoon, safari honeymoon package, luxury Tanzania honeymoon',
    'translations' => [
      'de' => ['title' => 'Flitterwochen-Safari Tanzania: Die romantischsten Safariziele 2026', 'excerpt' => 'Tansania ist das romantischste Safariziel der Welt. Entdecken Sie private Bush Camps, Candle-Light-Dinner im Busch, Heißluftballon-Sonnenaufgänge über der Serengeti und luxuriöse Sansibar-Strandabschlüsse.', 'category' => 'Planung'],
      'es' => ['title' => 'Safari de Luna de Miel en Tanzania: Los Destinos Más Románticos de 2026', 'excerpt' => 'Tanzania es el destino de safari más romántico del mundo. Descubra campamentos privados, cenas a la luz de las velas, amaneceres en globo sobre el Serengeti y preciosas playas de Zanzíbar.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚蜜月游猎：2026年最浪漫的游猎目的地', 'excerpt' => '坦桑尼亚是世界上最浪漫的游猎目的地。探索私人丛林营地、烛光丛林晚宴、塞伦盖蒂热气球日出和豪华桑给巴尔海滩收尾。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Balayı Safarisi: 2026\'nın En Romantik Safari Destinasyonları', 'excerpt' => 'Tanzanya, dünyanın en romantik safari destinasyonudur. Özel bush kampları, mum ışığında bush akşam yemekleri, Serengeti üzerinde balonla gün doğumu ve lüks Zanzibar plajları sizi bekliyor.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'great-migration-serengeti-calendar',
    'title' => 'Great Migration Serengeti Calendar 2026: Where to Be and When',
    'excerpt' => 'Track the Great Migration month by month across the Serengeti and Masai Mara. Find out exactly when and where to witness river crossings, calving season, and the full wildebeest circuit.',
    'meta_description' => 'Great Migration 2026 calendar. Month-by-month tracker for wildebeest migration — river crossings, calving season & best viewing areas in Serengeti.',
    'category' => 'Wildlife',
    'image' => '/images/blog/great-migration-serengeti-calendar.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-15',
    'read_time' => '11 min read',
    'featured' => true,
    'keywords' => 'Great Migration calendar, Serengeti wildebeest migration, when to see Great Migration, Mara river crossing, calving season Serengeti, migration 2026',
    'translations' => [
      'de' => ['title' => 'Große Migration Serengeti-Kalender 2026: Wo und Wann Sie sein sollten', 'excerpt' => 'Verfolgen Sie die Große Migration Monat für Monat durch die Serengeti und das Masai Mara. Erfahren Sie genau, wann und wo Sie Flussüberquerungen, die Kalbsaison und den gesamten Gnus-Kreislauf erleben können.', 'category' => 'Wildtiere'],
      'es' => ['title' => 'Calendario Gran Migración Serengeti 2026: Dónde Estar y Cuándo', 'excerpt' => 'Siga la Gran Migración mes a mes por el Serengeti y el Masai Mara. Descubra exactamente cuándo y dónde presenciar los cruces de río, la temporada de partos y el circuito completo de ñus.', 'category' => 'Fauna Silvestre'],
      'zh' => ['title' => '塞伦盖蒂大迁徙日历2026：何时何地最佳观赏', 'excerpt' => '逐月追踪穿越塞伦盖蒂和马赛马拉的大迁徙。了解何时何地可以观赏河流穿越、产犊季和完整的角马迁徙路线。', 'category' => '野生动物'],
      'tr' => ['title' => 'Serengeti Büyük Göç Takvimi 2026: Nerede ve Ne Zaman Olunmalı', 'excerpt' => 'Serengeti ve Masai Mara boyunca Büyük Göç\'ü ay ay takip edin. Nehir geçişlerini, doğum sezonunu ve tam antilop devresini tam olarak ne zaman ve nerede izleyeceğinizi öğrenin.', 'category' => 'Yaban Hayatı'],
    ],
  ],
  [
    'slug' => 'tanzania-safari-packing-list-2026',
    'title' => 'Tanzania Safari Packing List 2026: What to Bring (and What to Leave Behind)',
    'excerpt' => 'The definitive Tanzania safari packing list for 2026. Clothes, camera gear, medications, documents — everything you need organized by category with links to recommended gear.',
    'meta_description' => 'Tanzania safari packing list 2026. Complete gear guide: clothing, camera, medications, documents & pro tips from experienced guides.',
    'category' => 'Planning',
    'image' => '/images/blog/tanzania-safari-packing-list-2026.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-17',
    'read_time' => '7 min read',
    'featured' => false,
    'keywords' => 'Tanzania safari packing list, what to pack safari, safari clothing, safari camera gear, Tanzania travel checklist',
    'translations' => [
      'de' => ['title' => 'Tanzania Safari Packliste 2026: Was Sie Mitnehmen (und Was Sie Zuhause Lassen)', 'excerpt' => 'Die ultimative Tanzania-Safari-Packliste für 2026. Kleidung, Kameraausrüstung, Medikamente, Dokumente — alles was Sie brauchen, kategorisch sortiert mit Empfehlungen.', 'category' => 'Planung'],
      'es' => ['title' => 'Lista de Equipaje para Safari en Tanzania 2026: Qué Llevar (y Qué Dejar)', 'excerpt' => 'La lista definitiva de equipaje para safari en Tanzania 2026. Ropa, equipo fotográfico, medicamentos, documentos — todo organizado por categoría con recomendaciones de equipo.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚游猎行李清单2026：该带什么（以及该留下什么）', 'excerpt' => '2026年坦桑尼亚游猎终极行李清单。服装、摄影器材、药品、证件——按类别整理的所有必需品，附推荐装备链接。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Safari Bavul Listesi 2026: Ne Götürmeli (ve Ne Bırakmalı)', 'excerpt' => '2026 Tanzanya safari için nihai bavul listesi. Kıyafetler, kamera ekipmanları, ilaçlar, belgeler — kategoriye göre düzenlenmiş ihtiyaçlarınızın tamamı.', 'category' => 'Planlama'],
    ],
  ],
  [
    'slug' => 'nyerere-ruaha-southern-circuit-safari',
    'title' => 'Southern Tanzania Safari: Nyerere & Ruaha — Africa\'s Untouched Wilderness',
    'excerpt' => 'Skip the crowds on the Northern Circuit and discover Southern Tanzania\'s wild secret — Nyerere National Park and Ruaha. Enormous elephant herds, wild dogs, and zero other tourist vehicles.',
    'meta_description' => 'Southern Tanzania safari guide 2026. Nyerere National Park & Ruaha — less-crowded wilderness with huge elephants, wild dogs & spectacular landscapes.',
    'category' => 'Destinations',
    'image' => '/images/blog/nyerere-ruaha-southern-circuit-safari.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-19',
    'read_time' => '9 min read',
    'featured' => false,
    'keywords' => 'southern Tanzania safari, Nyerere National Park, Ruaha National Park, Selous Game Reserve, southern circuit Tanzania, off the beaten path safari',
    'translations' => [
      'de' => ['title' => 'Süd-Tanzania Safari: Nyerere & Ruaha — Afrikas unberührte Wildnis', 'excerpt' => 'Meiden Sie die Menschenmassen auf dem Northern Circuit und entdecken Sie Süd-Tanzanias wildes Geheimnis — den Nyerere-Nationalpark und Ruaha. Riesige Elefantenherden, Wildhunde und keine anderen Touristenfahrzeuge.', 'category' => 'Reiseziele'],
      'es' => ['title' => 'Safari en el Sur de Tanzania: Nyerere y Ruaha — La Naturaleza Virgen de África', 'excerpt' => 'Evite las multitudes del Circuito Norte y descubra el secreto salvaje del Sur de Tanzania — el Parque Nacional Nyerere y Ruaha. Enormes manadas de elefantes y cero otros vehículos turísticos.', 'category' => 'Destinos'],
      'zh' => ['title' => '坦桑尼亚南部游猎：尼耶雷尔与鲁阿哈——非洲未被触及的荒野', 'excerpt' => '跳过北部环线的游客人群，探索坦桑尼亚南部的野性秘境——尼耶雷尔国家公园和鲁阿哈。巨大的象群、野犬，以及零其他旅游车辆的纯野生体验。', 'category' => '目的地'],
      'tr' => ['title' => 'Güney Tanzanya Safarisi: Nyerere ve Ruaha — Afrika\'nın Dokunulmamış Vahşi Doğası', 'excerpt' => 'Kuzey Devresi\'nin kalabalıklarını atlayın ve Güney Tanzanya\'nın vahşi sırrını keşfedin — Nyerere Milli Parkı ve Ruaha. Devasa fil sürüleri, yaban köpekleri ve sıfır turist aracı.', 'category' => 'Destinasyonlar'],
    ],
  ],
  [
    'slug' => 'tanzania-visa-guide-2026',
    'title' => 'Tanzania Visa Requirements 2026: Everything You Need to Know Before You Go',
    'excerpt' => 'Complete Tanzania visa guide for 2026. Who needs a visa, how to apply for the Tanzania e-Visa online, costs, processing time, and entry requirements for over 50 nationalities.',
    'meta_description' => 'Tanzania visa requirements 2026. E-Visa application guide, cost ($50 USD), processing time, and entry requirements for US, UK, EU & other nationalities.',
    'category' => 'Planning',
    'image' => '/images/blog/tanzania-visa-guide-2026.jpg',
    'author' => 'iTanzania Safaris',
    'date' => '2026-03-20',
    'read_time' => '7 min read',
    'featured' => false,
    'keywords' => 'Tanzania visa requirements, Tanzania e-visa, Tanzania visa 2026, Tanzania entry requirements, Tanzania visa cost, Tanzania tourist visa',
    'translations' => [
      'de' => ['title' => 'Tanzania Visumsanforderungen 2026: Alles was Sie vor der Abreise wissen müssen', 'excerpt' => 'Vollständiger Tanzania-Visumsleitfaden für 2026. Wer braucht ein Visum, wie man das Tanzania e-Visum online beantragt, Kosten, Bearbeitungszeit und Einreisebestimmungen für über 50 Nationalitäten.', 'category' => 'Planung'],
      'es' => ['title' => 'Requisitos de Visa para Tanzania 2026: Todo lo que Necesitas Saber Antes de Ir', 'excerpt' => 'Guía completa de visa para Tanzania 2026. Quién necesita visa, cómo solicitar la e-Visa en línea, costos, tiempo de procesamiento y requisitos de entrada para más de 50 nacionalidades.', 'category' => 'Planificación'],
      'zh' => ['title' => '坦桑尼亚签证要求2026：出发前需要了解的一切', 'excerpt' => '2026年坦桑尼亚签证完整指南。谁需要签证、如何在线申请坦桑尼亚电子签证、费用、处理时间以及50多个国籍的入境要求。', 'category' => '行程规划'],
      'tr' => ['title' => 'Tanzanya Vize Gereksinimleri 2026: Gitmeden Önce Bilmeniz Gereken Her Şey', 'excerpt' => '2026 Tanzanya vize rehberi. Kimin vizeye ihtiyacı var, Tanzanya e-Vizesi nasıl başvurulur, maliyetler, işlem süresi ve 50\'den fazla uyruk için giriş gereksinimleri.', 'category' => 'Planlama'],
    ],
  ],
];

/**
 * Return a post array with title/excerpt/category translated for $lang.
 */
function localizePost($post, $lang) {
  if ($lang !== 'en' && isset($post['translations'][$lang])) {
    $t = $post['translations'][$lang];
    if (isset($t['title']))    $post['title']    = $t['title'];
    if (isset($t['excerpt']))  $post['excerpt']  = $t['excerpt'];
    if (isset($t['category'])) $post['category'] = $t['category'];
  }
  return $post;
}

function getBlogBySlug($slug) {
  global $blogPosts;
  foreach ($blogPosts as $post) {
    if ($post['slug'] === $slug) return $post;
  }
  return null;
}

function getFeaturedPosts() {
  global $blogPosts;
  return array_filter($blogPosts, fn($p) => $p['featured']);
}

function getRelatedPosts($currentSlug, $category, $limit = 3) {
  global $blogPosts;
  $related = array_filter($blogPosts, fn($p) => $p['slug'] !== $currentSlug && $p['category'] === $category);
  if (count($related) < $limit) {
    $others = array_filter($blogPosts, fn($p) => $p['slug'] !== $currentSlug && $p['category'] !== $category);
    $related = array_merge($related, array_slice($others, 0, $limit - count($related)));
  }
  return array_slice($related, 0, $limit);
}
