<?php
/**
 * Tours Data - All tour packages
 */

$safariTours = [
  [
    'id' => 'great-migration',
    'title' => 'Great Migration Safari',
    'duration' => '8 Days / 7 Nights',
    'groupSize' => '2-6 Travelers',
    'price' => 4500,
    'originalPrice' => 5500,
    'image' => 'images/serengeti.jpg',
    'badge' => 'Most Popular',
    'spotsLeft' => 4,
    'shortDescription' => 'Witness the greatest wildlife spectacle on Earth. Follow millions of wildebeest across the Serengeti in this once-in-a-lifetime safari.',
    'description' => 'Witness nature\'s greatest spectacle as over two million wildebeest, zebras, and gazelles thunder across the Serengeti in their annual migration. This carefully timed safari puts you right in the heart of the action, with expert guides who know exactly where the herds will be.',
    'highlights' => ['Witness the Great Migration river crossings', 'Big Five game drives in the Serengeti', 'Ngorongoro Crater descent', 'Luxury tented camps under the stars', 'Expert local guides with 10+ years experience', 'Small group size for intimate experiences'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Arrival in Arusha', 'description' => 'Welcome at Kilimanjaro Airport. Transfer to your luxury hotel in Arusha for a briefing dinner.'],
      ['day' => 'Day 2', 'title' => 'Tarangire National Park', 'description' => 'Full day game drive in Tarangire, famous for massive elephant herds and iconic baobab trees.'],
      ['day' => 'Day 3', 'title' => 'Ngorongoro Crater', 'description' => 'Descend into the world\'s largest intact caldera for incredible Big Five game viewing.'],
      ['day' => 'Day 4-5', 'title' => 'Serengeti - Central', 'description' => 'Two full days exploring the central Serengeti plains. Witness predator-prey interactions.'],
      ['day' => 'Day 6-7', 'title' => 'Serengeti - Northern/Western', 'description' => 'Follow the migration to river crossing points. Witness the dramatic Mara River crossings.'],
      ['day' => 'Day 8', 'title' => 'Departure', 'description' => 'Morning game drive, then fly back to Arusha. Transfer to airport for departure.'],
    ],
    'included' => ['All park and conservation fees', 'Professional English-speaking safari guide', 'Luxury tented camp accommodation', 'All meals during safari', 'Private 4x4 safari vehicle', 'Drinking water throughout', 'Airport transfers', 'Flying Doctors emergency evacuation insurance'],
    'excluded' => ['International flights', 'Visa fees', 'Travel insurance', 'Tips and gratuities', 'Personal expenses', 'Optional balloon safari ($599)'],
  ],
  [
    'id' => 'big-five-luxury',
    'title' => 'Big Five Luxury Safari',
    'duration' => '6 Days / 5 Nights',
    'groupSize' => '2-4 Travelers',
    'price' => 5800,
    'originalPrice' => null,
    'image' => 'images/big-five.jpg',
    'badge' => 'Premium',
    'spotsLeft' => null,
    'shortDescription' => 'An exclusive luxury safari experience with premium lodges, private game drives, and intimate wildlife encounters in the finest parks.',
    'description' => 'Experience Tanzania\'s finest wildlife encounters in ultimate luxury. This exclusive safari features premium lodges, private game drives, and intimate experiences designed for the most discerning traveler. Every detail is crafted for comfort and unforgettable moments.',
    'highlights' => ['Private game drives in luxury vehicle', 'Premium lodge accommodation', 'All Big Five guaranteed sighting areas', 'Sunset cocktails on the savanna', 'Bush breakfast and dinner experiences', 'Dedicated personal safari guide'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'VIP Arrival', 'description' => 'Private airport transfer. Welcome dinner at luxury Arusha hotel with safari briefing.'],
      ['day' => 'Day 2', 'title' => 'Lake Manyara', 'description' => 'Explore Lake Manyara\'s tree-climbing lions, flamingo-lined shores, and lush forests.'],
      ['day' => 'Day 3', 'title' => 'Ngorongoro Crater', 'description' => 'Full day in the crater with gourmet picnic lunch. Unrivaled Big Five viewing.'],
      ['day' => 'Day 4-5', 'title' => 'Serengeti', 'description' => 'Two days in the Serengeti with bush breakfast, sunset drives, and star-gazing.'],
      ['day' => 'Day 6', 'title' => 'Farewell', 'description' => 'Final morning drive. Scenic flight back to Arusha. Farewell lunch and departure.'],
    ],
    'included' => ['All park and conservation fees', 'Private luxury 4x4 with pop-up roof', 'Premium lodge and tented camp accommodation', 'All gourmet meals and premium beverages', 'Internal scenic flights where applicable', 'Private professional safari guide', 'Laundry service', 'All airport transfers', 'Emergency evacuation insurance'],
    'excluded' => ['International flights', 'Visa fees', 'Travel insurance', 'Tips', 'Premium wines and spirits'],
  ],
  [
    'id' => 'family-safari',
    'title' => 'Family Safari Adventure',
    'duration' => '7 Days / 6 Nights',
    'groupSize' => '2-8 Travelers',
    'price' => 3200,
    'originalPrice' => 3800,
    'image' => 'images/family-safari.jpg',
    'badge' => 'Family Friendly',
    'spotsLeft' => null,
    'shortDescription' => 'A safari designed for families with children, featuring kid-friendly activities, educational experiences, and comfortable family lodges.',
    'description' => 'Designed specifically for families, this safari combines wildlife adventure with educational experiences that kids of all ages will love. Family-friendly lodges with pools, junior ranger programs, and guides specially trained to engage young minds.',
    'highlights' => ['Junior ranger activity booklets', 'Family-sized safari vehicles', 'Kid-friendly lodges with swimming pools', 'Educational wildlife programs', 'Cultural village visits', 'Flexible pace and scheduling'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Family Welcome', 'description' => 'Airport pickup, kid-friendly hotel in Arusha. Evening briefing with junior ranger packs.'],
      ['day' => 'Day 2', 'title' => 'Cultural Experience', 'description' => 'Visit a Maasai village and coffee plantation. Interactive experiences for all ages.'],
      ['day' => 'Day 3-4', 'title' => 'Serengeti Adventure', 'description' => 'Two days of family game drives. Kids spot animals from their activity checklists.'],
      ['day' => 'Day 5', 'title' => 'Ngorongoro Crater', 'description' => 'Full day crater safari. Picnic lunch with views. Evening swimming pool time.'],
      ['day' => 'Day 6', 'title' => 'Tarangire', 'description' => 'Elephant herds and baobab trees. Night safari option for older kids.'],
      ['day' => 'Day 7', 'title' => 'Departure', 'description' => 'Morning at leisure, departure transfers. Junior ranger certificates awarded!'],
    ],
    'included' => ['All park fees (children\'s rates applied)', 'Family safari vehicle', 'Family rooms/tents at all accommodations', 'All meals', 'Junior ranger activity packs', 'Cultural village visit', 'All transfers', 'Emergency insurance'],
    'excluded' => ['International flights', 'Visa fees', 'Travel insurance', 'Tips', 'Optional activities'],
  ],
];

$kilimanjaroTours = [
  [
    'id' => 'machame-route',
    'title' => 'Machame Route - Whiskey Route',
    'duration' => '7 Days / 6 Nights',
    'groupSize' => '2-10 Climbers',
    'price' => 2800,
    'originalPrice' => 3200,
    'image' => 'images/machame.jpg',
    'badge' => 'Most Popular',
    'spotsLeft' => 6,
    'shortDescription' => 'The most popular route up Kilimanjaro, known for its stunning scenery and high success rate. A challenging but incredibly rewarding trek.',
    'description' => 'The Machame Route is the most popular path up Kilimanjaro for good reason. Known as the "Whiskey Route" for its challenging terrain, it offers stunning scenery through diverse ecological zones and has an impressive 90%+ summit success rate with proper acclimatization.',
    'highlights' => ['90%+ summit success rate', 'Most scenic route on Kilimanjaro', 'Diverse ecological zones (rainforest to arctic)', 'Challenging and rewarding trek', 'Excellent acclimatization profile', 'Professional mountain crew'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Machame Gate to Machame Camp', 'description' => 'Trek through lush montane rainforest. Elevation: 1,800m to 3,000m.'],
      ['day' => 'Day 2', 'title' => 'Machame Camp to Shira Camp', 'description' => 'Ascend through heath and moorland to the Shira Plateau. Elevation: 3,000m to 3,840m.'],
      ['day' => 'Day 3', 'title' => 'Shira to Barranco Camp', 'description' => 'Acclimatization hike to Lava Tower (4,630m), then descend to Barranco. Elevation: 3,840m to 3,960m.'],
      ['day' => 'Day 4', 'title' => 'Barranco to Karanga Camp', 'description' => 'Climb the famous Barranco Wall and cross the alpine desert. Elevation: 3,960m to 3,995m.'],
      ['day' => 'Day 5', 'title' => 'Karanga to Barafu Camp', 'description' => 'Short but steep hike to high camp. Rest and prepare for summit. Elevation: 3,995m to 4,673m.'],
      ['day' => 'Day 6', 'title' => 'Summit Day - Uhuru Peak!', 'description' => 'Pre-dawn start. Reach Stella Point then Uhuru Peak (5,895m). Sunrise over Africa. Descend to Mweka Camp.'],
      ['day' => 'Day 7', 'title' => 'Descent & Celebration', 'description' => 'Trek down to Mweka Gate. Certificates and celebration lunch. Transfer to hotel in Moshi.'],
    ],
    'included' => ['All park and rescue fees', 'Certified KINAPA mountain guide', 'Porters and professional cook', 'Quality mountain tents and sleeping mats', 'All meals on the mountain', 'Pulse oximeter health monitoring', 'Emergency oxygen', '1 night hotel before and after climb', 'All airport transfers', 'Summit certificate'],
    'excluded' => ['International flights', 'Visa fees', 'Climbing insurance', 'Tips for crew', 'Personal gear'],
  ],
  [
    'id' => 'lemosho-route',
    'title' => 'Lemosho Route - Premium Trek',
    'duration' => '8 Days / 7 Nights',
    'groupSize' => '2-8 Climbers',
    'price' => 3400,
    'originalPrice' => 3800,
    'image' => 'images/lemosho.jpg',
    'badge' => 'Highest Success',
    'spotsLeft' => null,
    'shortDescription' => 'The premium route with the highest success rate. Remote approach, spectacular scenery, and the best acclimatization profile.',
    'description' => 'The Lemosho Route is considered the finest way up Kilimanjaro. Starting from the remote west side, it offers pristine wilderness, spectacular views across the Shira Plateau, and the best acclimatization profile of any route, resulting in a 95%+ summit success rate.',
    'highlights' => ['95%+ summit success rate', 'Remote and uncrowded trail', 'Spectacular Shira Plateau crossing', 'Best acclimatization profile', 'Premium camping equipment', 'Experienced mountain crew'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Londorossi Gate to Big Tree Camp', 'description' => 'Drive to Londorossi Gate. Trek through pristine rainforest. Elevation: 2,100m to 2,780m.'],
      ['day' => 'Day 2', 'title' => 'Big Tree Camp to Shira 1 Camp', 'description' => 'Continue through forest to moorland. Stunning views open up. Elevation: 2,780m to 3,500m.'],
      ['day' => 'Day 3', 'title' => 'Shira 1 to Shira 2 Camp', 'description' => 'Cross the magnificent Shira Plateau beneath Kibo\'s western breach. Elevation: 3,500m to 3,840m.'],
      ['day' => 'Day 4', 'title' => 'Shira 2 to Barranco Camp', 'description' => 'Acclimatization hike to Lava Tower (4,630m), descend to Barranco. Elevation: 3,840m to 3,960m.'],
      ['day' => 'Day 5', 'title' => 'Barranco to Karanga Camp', 'description' => 'Climb the Barranco Wall and cross alpine desert to Karanga. Elevation: 3,960m to 3,995m.'],
      ['day' => 'Day 6', 'title' => 'Karanga to Barafu Camp', 'description' => 'Final approach to high camp. Rest and prepare for summit. Elevation: 3,995m to 4,673m.'],
      ['day' => 'Day 7', 'title' => 'Summit Day - Uhuru Peak!', 'description' => 'Pre-dawn ascent to the Roof of Africa at 5,895m. Witness an unforgettable sunrise. Descend to Mweka Camp.'],
      ['day' => 'Day 8', 'title' => 'Descent & Celebration', 'description' => 'Trek down to Mweka Gate. Certificates and celebrations. Transfer to hotel in Moshi.'],
    ],
    'included' => ['All park and rescue fees', 'Senior mountain guide (10+ years experience)', 'Porters and professional cook', 'Premium mountain tents and equipment', 'All meals on the mountain (gourmet menu)', 'Private portable toilet', 'Pulse oximeter and oxygen system', '2 nights hotel accommodation', 'All airport transfers', 'Summit certificate and celebration dinner'],
    'excluded' => ['International flights', 'Visa fees', 'Climbing insurance', 'Tips for crew', 'Personal gear'],
  ],
  [
    'id' => 'marangu-route',
    'title' => 'Marangu Route - Coca Cola Route',
    'duration' => '6 Days / 5 Nights',
    'groupSize' => '2-12 Climbers',
    'price' => 2200,
    'originalPrice' => null,
    'image' => 'images/marangu.jpg',
    'badge' => 'Classic Route',
    'spotsLeft' => null,
    'shortDescription' => 'The classic route with comfortable hut accommodation. The only route offering sleeping huts instead of tents.',
    'description' => 'The Marangu Route is the oldest and most established path up Kilimanjaro. It\'s the only route that offers sleeping huts with mattresses, making it popular with those who prefer not to camp. The gentle gradient makes it suitable for less experienced trekkers.',
    'highlights' => ['Comfortable hut accommodation', 'Gentle gradient suitable for beginners', 'The classic Kilimanjaro experience', 'Well-maintained trail', 'Same route up and down', 'Hot meals at hut camps'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Marangu Gate to Mandara Hut', 'description' => 'Trek through beautiful rainforest to Mandara Hut. Elevation: 1,860m to 2,700m.'],
      ['day' => 'Day 2', 'title' => 'Mandara to Horombo Hut', 'description' => 'Cross moorland with views of Kibo and Mawenzi peaks. Elevation: 2,700m to 3,720m.'],
      ['day' => 'Day 3', 'title' => 'Acclimatization Day at Horombo', 'description' => 'Day hike to Zebra Rocks (4,000m) for acclimatization. Return to Horombo for rest.'],
      ['day' => 'Day 4', 'title' => 'Horombo to Kibo Hut', 'description' => 'Cross the alpine desert saddle between Mawenzi and Kibo. Elevation: 3,720m to 4,700m.'],
      ['day' => 'Day 5', 'title' => 'Summit Night!', 'description' => 'Midnight departure. Reach Gilman\'s Point (5,685m), then push to Uhuru Peak (5,895m). Descend to Horombo.'],
      ['day' => 'Day 6', 'title' => 'Descent to Gate', 'description' => 'Final descent through rainforest to Marangu Gate. Certificates and transfer to hotel.'],
    ],
    'included' => ['All park and rescue fees', 'Certified mountain guide', 'Porters and cook', 'Hut accommodation with mattresses', 'All meals on the mountain', 'First aid and oxygen', 'Hotel night before and after climb', 'Airport transfers', 'Summit certificate'],
    'excluded' => ['International flights', 'Visa fees', 'Insurance', 'Tips', 'Personal gear'],
  ],
];

$zanzibarTours = [
  [
    'id' => 'zanzibar-beach-escape',
    'title' => 'Zanzibar Beach Escape',
    'duration' => '5 Days / 4 Nights',
    'groupSize' => '2-6 Travelers',
    'price' => 1800,
    'originalPrice' => 2200,
    'image' => 'images/zanzibar-beach.jpg',
    'badge' => 'Best Value',
    'spotsLeft' => 8,
    'shortDescription' => 'Relax on pristine white-sand beaches, explore Stone Town\'s historic streets, and snorkel in crystal-clear turquoise waters.',
    'description' => 'Unwind in tropical paradise on Zanzibar\'s stunning coast. This perfectly balanced getaway combines relaxation on powder-white beaches with cultural exploration of UNESCO-listed Stone Town and underwater adventures in the Indian Ocean.',
    'highlights' => ['Pristine white-sand beaches', 'UNESCO Stone Town walking tour', 'Snorkeling at Mnemba Atoll', 'Spice farm tour', 'Beachfront boutique hotel', 'Sunset dhow cruise'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Arrival in Stone Town', 'description' => 'Welcome at Zanzibar Airport. Transfer to a charming boutique hotel in the heart of historic Stone Town. Evening rooftop dinner.'],
      ['day' => 'Day 2', 'title' => 'Stone Town & Spice Tour', 'description' => 'Morning walking tour of Stone Town\'s winding alleys, markets, and historic buildings. Afternoon spice plantation visit.'],
      ['day' => 'Day 3', 'title' => 'Beach Transfer & Relaxation', 'description' => 'Transfer to your beachfront resort on the east coast. Afternoon at leisure on pristine white sand.'],
      ['day' => 'Day 4', 'title' => 'Snorkeling & Sunset Cruise', 'description' => 'Morning snorkeling trip to Mnemba Atoll with dolphins and sea turtles. Evening sunset dhow cruise with seafood dinner.'],
      ['day' => 'Day 5', 'title' => 'Departure', 'description' => 'Morning beach time, then transfer to airport for departure.'],
    ],
    'included' => ['Airport transfers', '2 nights boutique hotel in Stone Town', '2 nights beachfront resort', 'Daily breakfast and select meals', 'Stone Town guided walking tour', 'Spice plantation tour', 'Snorkeling trip to Mnemba Atoll', 'Sunset dhow cruise with dinner'],
    'excluded' => ['International flights', 'Visa fees', 'Travel insurance', 'Tips', 'Personal expenses'],
  ],
  [
    'id' => 'honeymoon-zanzibar',
    'title' => 'Romantic Honeymoon Package',
    'duration' => '7 Days / 6 Nights',
    'groupSize' => '2 Travelers',
    'price' => 3500,
    'originalPrice' => 4200,
    'image' => 'images/honeymoon.jpg',
    'badge' => 'Romance',
    'spotsLeft' => null,
    'shortDescription' => 'An exclusive honeymoon escape with private villa, couples spa, candlelit beach dinners, and unforgettable sunset moments.',
    'description' => 'Celebrate your love in the most romantic setting imaginable. This exclusive honeymoon package combines luxury, privacy, and unforgettable experiences in Zanzibar\'s most stunning locations.',
    'highlights' => ['Private beachfront villa with plunge pool', 'Couples spa treatments', 'Candlelit dinner on the beach', 'Private sunset sailing', 'Champagne breakfast in bed', 'Romantic Stone Town evening'],
    'itinerary' => [
      ['day' => 'Day 1', 'title' => 'Romantic Arrival', 'description' => 'VIP airport welcome with flower garlands. Private transfer to your oceanfront villa. Champagne and tropical fruit welcome.'],
      ['day' => 'Day 2', 'title' => 'Stone Town Romance', 'description' => 'Private guided tour of Stone Town, rooftop lunch, couples\' perfume-making workshop. Evening at the famous Forodhani night market.'],
      ['day' => 'Day 3-4', 'title' => 'Beach Paradise', 'description' => 'Two days of pure relaxation. Couples spa treatment, private beach picnic, kayaking, and yoga sessions.'],
      ['day' => 'Day 5', 'title' => 'Ocean Adventures', 'description' => 'Private boat to Mnemba Island for snorkeling. Dolphin watching. Candlelit beach dinner under the stars.'],
      ['day' => 'Day 6', 'title' => 'Sunset Sailing', 'description' => 'Lazy morning with breakfast in bed. Afternoon private dhow sailing trip with champagne and sunset views.'],
      ['day' => 'Day 7', 'title' => 'Farewell', 'description' => 'Final breakfast on your private terrace. Flower bath preparation. Transfer to airport with honeymoon memories.'],
    ],
    'included' => ['Private airport transfers', '6 nights luxury beachfront villa', 'All meals at resort', 'Couples spa treatment package', 'Private Stone Town tour', 'Candlelit beach dinner for two', 'Private sunset dhow cruise', 'Mnemba Island snorkeling trip', 'Champagne and flowers on arrival', 'Honeymoon room decoration'],
    'excluded' => ['International flights', 'Visa fees', 'Travel insurance', 'Tips', 'Additional spa treatments'],
  ],
  [
    'id' => 'safari-beach-combo',
    'title' => 'Safari & Beach Combo',
    'duration' => '10 Days / 9 Nights',
    'groupSize' => '2-6 Travelers',
    'price' => 5200,
    'originalPrice' => 6000,
    'image' => 'images/safari-beach.jpg',
    'badge' => 'Best of Both',
    'spotsLeft' => 3,
    'shortDescription' => 'The ultimate Tanzania experience combining world-class Serengeti safaris with Zanzibar beach relaxation.',
    'description' => 'Why choose between safari and beach when you can have both? This comprehensive package pairs thrilling wildlife encounters in the Serengeti and Ngorongoro with blissful beach days on Zanzibar\'s pristine coast.',
    'highlights' => ['Serengeti game drives', 'Ngorongoro Crater descent', 'Zanzibar white-sand beaches', 'Stone Town exploration', 'Snorkeling and water sports', 'The complete Tanzania experience'],
    'itinerary' => [
      ['day' => 'Day 1-2', 'title' => 'Serengeti Safari', 'description' => 'Fly to the Serengeti for two days of incredible game drives. Luxury tented camp with savanna views.'],
      ['day' => 'Day 3', 'title' => 'Ngorongoro Crater', 'description' => 'Descend into the crater for a full day game drive. Spot the Big Five in this natural amphitheater.'],
      ['day' => 'Day 4-5', 'title' => 'Tarangire & Transfer', 'description' => 'Morning game drive in Tarangire. Afternoon flight to Zanzibar. Settle into your beachfront hotel.'],
      ['day' => 'Day 6', 'title' => 'Stone Town Discovery', 'description' => 'Full day exploring UNESCO-listed Stone Town. Spice tour and evening food market.'],
      ['day' => 'Day 7-9', 'title' => 'Beach Paradise', 'description' => 'Three glorious days on the beach. Snorkeling, sunset cruise, and pure relaxation.'],
      ['day' => 'Day 10', 'title' => 'Departure', 'description' => 'Final morning on the beach before airport transfer and departure.'],
    ],
    'included' => ['All safari park fees', 'Internal flights (Arusha-Serengeti, Arusha-Zanzibar)', '3 nights luxury safari accommodation', '6 nights beachfront resort in Zanzibar', 'All safari meals', 'Beach hotel breakfast daily', 'Private safari vehicle and guide', 'Stone Town guided tour', 'Snorkeling excursion', 'Sunset dhow cruise', 'All airport transfers'],
    'excluded' => ['International flights', 'Visa fees', 'Travel insurance', 'Tips', 'Lunches and dinners in Zanzibar'],
  ],
];
?>
